name: Maven CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  release:
    types: [published]

jobs:
  validate:
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven/build-test.yml@main
    with:
      java-version: 17
      java-distribution: temurin
    secrets: inherit

  spotless:
    needs: validate
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven/spotless-check.yml@main
    with:
      java-version: 17
      java-distribution: temurin

  # this job publishes snapshots on every push to main
  pre-release:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: validate
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven/publish.yml@main
    with:
      java-version: 17
      java-distribution: temurin
      maven-args: -DskipTests
    secrets: inherit

  # this job publishes releases on every tag
  release:
    if: ${{ github.event_name == 'release' }}
    needs: validate
    uses: mekomsolutions/shared-github-workflow/.github/workflows/maven/publish.yml@main
    with:
      java-version: 17
      java-distribution: temurin
      maven-args: -DskipTests
    secrets: inherit

  # this job notifies OCD3 of a new pre-release(snapshots)
  notify-ocd3:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    needs: pre-release
    uses: mekomsolutions/shared-github-workflow/.github/workflows/ocd3/notify.yml@main
    with:
      notify-ocd3: true
      webhook-url: https://openmrs-cd.mekomsolutions.net/generic-webhook-trigger/invoke
    secrets: inherit
